### ISSUE TITLE
Invite Emails not being sent

### ISSUE THREAD

**Issue by Brandogs** [knowmetools/km-api#342] opened 2018-06-06 17:37 UTC
Emails notifying the user that they have been invited to follow a profile are not being sent. Text of email should be:

<html>
<body>
<h3>You have been invited to learn more about [[name]] with the Know Me iOS app.</h3>
Use this email address to log into Know Me and view your invitation.
<br/><br/>
<b>If you do not have Know Me:</b><br/>
No problem. You can 
<a href="https://itunes.apple.com/us/app/know-me-profile-communication/id1051805757?mt=8">download the app for free</a> on your iPad or iPhone from the App Store. 
<br/><br/>
Thanks, 
<br/>
The Know Me team
</body>
</html>

**Comment by cdriehuys** [comment] 2018-06-06 21:08
This is a duplicate of #236.

**Closed by cdriehuys** 2018-06-06 21:08 UTC
